version: "3.7"

services:

  spring-boot-cassandra-app:
    image: spring-boot-cassandra:0.0.1-SNAPSHOT
    container_name: cassandra-app
    ports:
      - "8080:8080"
    networks:
      - cassandra

networks:
  cassandra:
    driver: bridge